services:
  - type: web
    name: catalogo-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ServidorActualizacion:app
    envVars:
      - key: ADMIN_KEY
        value: Zombie2
      - key: ADMIN_PORT
        value: 8000
